# Generated by Django 4.2.7 on 2026-09-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costapproval",
            name="executing_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executed_approvals",
                to="settlement.institution",
            ),
        ),
        migrations.AlterField(
            model_name="costapproval",
            name="insurance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approvals",
                to="settlement.insurance",
            ),
        ),
        migrations.AlterField(
            model_name="costapproval",
            name="ordering_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordered_approvals",
                to="settlement.institution",
            ),
        ),
    ]
