# Generated by Django 4.2.7 on 2026-06-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("settlement", "0001_initial"),
        ("core", "0006_merge_0005_create_test_user_0005_translation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("attended", models.BooleanField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("series_id", models.UUIDField(blank=True, null=True)),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.dependent",
                    ),
                ),
                (
                    "institutions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appointments",
                        to="settlement.institution",
                    ),
                ),
            ],
        ),
    ]
