# Generated by Django 6.0.5 on 2026-05-22 18:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_create_admin_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("main_diagnosis", models.CharField(max_length=255)),
                (
                    "ahv_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="AHV number must be in the format 756.xxxx.xxxx.xx",
                                regex="^756\\.\\d{4}\\.\\d{4}\\.\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="dependents", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
