# Generated by Django 4.2.7 on 2026-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependent",
            name="is_encrypted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="ahv_number",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="first_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="last_name",
            field=models.CharField(max_length=500),
        ),
    ]
