# Generated by Django 4.2.7 on 2026-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("en", models.TextField(blank=True, null=True)),
                ("de", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
