# Generated by Django 4.2.7 on 2026-05-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_create_test_user"),
        ("core", "0005_translation"),
    ]

    operations = []
