# Generated by Django 4.2.7 on 2026-06-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0005_dependent_is_encrypted_alter_dependent_ahv_number_and_more",
        ),
        ("core", "0006_merge_0005_create_test_user_0005_translation"),
    ]

    operations = []
