# Generated by Django 4.2.7 on 2026-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0007_merge_0005_dependent_is_encrypted_alter_dependent_ahv_number_and_more_0006_merge_0005_create_test_user_0005_translation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="module_assistants_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="module_documents_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="module_health_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="module_schedule_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="module_settlement_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
