# Generated by Django 4.2.7 on 2026-10-08 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_profile_module_assistants_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependent",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dependent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dependent",
            name="emergency_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dependent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="ahv_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="main_diagnosis",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
