# Generated by Django 4.2.7 on 2026-10-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_dependent_birth_date_dependent_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependent",
            name="ahv_number",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
