# Generated by Django 4.2.7 on 2026-09-15 13:41

import assistants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hourly_wage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Always uses hourly wage, no monthly salary.",
                        max_digits=8,
                    ),
                ),
                (
                    "target_hours_per_week",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("probation_period_months", models.IntegerField(default=3)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "basic_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sick_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "holiday_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Spesen", max_digits=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="assistants.contract",
                    ),
                ),
            ],
            options={
                "unique_together": {("contract", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gross_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ahv_iv_eo_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "alv_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "bvg_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "source_tax_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "employer_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Nebenkosten des Arbeitgebers",
                        max_digits=10,
                    ),
                ),
                (
                    "pdf_document",
                    models.FileField(blank=True, null=True, upload_to="payslips/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "working_hours",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslip",
                        to="assistants.workinghours",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "ahv_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[assistants.models.validate_ahv_number],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IV_ASSISTANCE", "IV Assistance"),
                            ("DOMESTIC", "Domestic Employee"),
                            ("BABYSITTER", "Babysitter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contract",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to="assistants.employee",
            ),
        ),
    ]
